### ISSUE TITLE
Error loading conanfile at '/home/nombre_de_usuario/Documentos/googletrans-master/conanfile.py' conan 2.4.0

### ISSUE THREAD

**Issue by Sturm0** [nidhaloff/googletrans#1]
```
nombre_de_usuario@nombre_de_usuario-PC-ESCRITORIO:~/Documentos/googletrans-master$ make clean 
rm -rf build && mkdir -p build && cd build && conan install .. --build=missing

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

ERROR: Error loading conanfile at '/home/nombre_de_usuario/Documentos/googletrans-master/conanfile.py': Unable to load conanfile in /home/nombre_de_usuario/Documentos/googletrans-master/conanfile.py
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/nombre_de_usuario/Documentos/googletrans-master/conanfile.py", line 1, in <module>
    from conans import ConanFile
ImportError: cannot import name 'ConanFile' from 'conans' (/opt/conan/bin/_internal/conans/__init__.pyc)

make: *** [makefile:3: clean] Error 1
```
This error appears when I try to use it with conan 2.4.0 (on Ubuntu MATE 24.04).

But it seems to be working fine on conan 1.64.1 (also on Ubuntu MATE 24.04).
